[build]
builder = "NIXPACKS"
buildCommand = "npx expo export --platform web"

[deploy]
startCommand = "npx serve dist --listen $PORT"
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
